-- =============================================================================
-- 009_notifications.sql
-- In-app notifications delivered to individual users.
-- Notifications are generated by the system or backend RPC functions.
-- =============================================================================

create table if not exists public.notifications (

    id uuid primary key
        default gen_random_uuid(),

    user_id uuid not null
        references public.users(id)
        on delete cascade,

    reference text
        unique,

    title text
        not null,

    body text,

    notification_type public.notification_type
        not null,

    action_url text,

    metadata jsonb
        not null
        default '{}'::jsonb,

    is_read boolean
        not null
        default false,

    read_at timestamptz,

    created_at timestamptz
        not null
        default timezone('utc', now()),

    updated_at timestamptz
        not null
        default timezone('utc', now()),

    constraint notifications_read_consistency
    check (
        (is_read = false and read_at is null)
        or
        (is_read = true and read_at is not null)
    )

);

-- =============================================================================
-- COMMENTS
-- =============================================================================

comment on table public.notifications is
'Stores in-app notifications sent to users.';

comment on column public.notifications.reference is
'Optional unique notification reference for tracing and debugging.';

comment on column public.notifications.action_url is
'Frontend route opened when the user taps the notification.';

comment on column public.notifications.metadata is
'Additional notification-specific information stored as JSON.';

comment on column public.notifications.read_at is
'Timestamp when the notification was marked as read.';

-- =============================================================================
-- INDEXES
-- =============================================================================

create index if not exists notifications_user_read_idx
    on public.notifications(user_id, is_read);

create index if not exists notifications_created_at_idx
    on public.notifications(created_at desc);

create index if not exists notifications_type_idx
    on public.notifications(notification_type);

create index if not exists notifications_reference_idx
    on public.notifications(reference);

-- -- =============================================================================
-- -- 009_notifications.sql
-- -- In-app notifications delivered to a specific user.
-- -- =============================================================================

-- create table if not exists public.notifications (
--   id                  uuid primary key default gen_random_uuid(),
--   user_id             uuid not null references public.users(id) on delete cascade,
--   title               text not null,
--   body                text,
--   notification_type   public.notification_type not null,
--   is_read             boolean not null default false,
--   created_at          timestamptz not null default now()
-- );

-- comment on table public.notifications is 'In-app notifications, created via create_notification().';

-- create index if not exists notifications_user_id_is_read_idx on public.notifications(user_id, is_read);
-- create index if not exists notifications_created_at_idx on public.notifications(created_at desc);